In [1]:
import pandas
import time

In [2]:
import sys

sys.path.append("../../")
import phitter

In [3]:
df_fit_time = pandas.DataFrame()

In [4]:
# SAMPLE_SIZES = [100, 1000, 10000, 100000, 1000000]
SAMPLE_SIZES = [10, 100]

In [5]:
for distribution_name, distribution_class in phitter.continuous.ALL_CONTINUOUS_DISTRIBUTIONS.items():
    for size in SAMPLE_SIZES:
        sample = distribution_class(init_parameters_examples=True).sample(size)
        continuous_measures = phitter.continuous.CONTINUOUS_MEASURES(sample)
        ti = time.time()
        distribution = distribution_class(continuous_measures)
        tf = time.time() - ti
        df_fit_time.loc[distribution_name, size] = round(tf, 4)

alpha 10
alpha 100
arcsine 10
arcsine 100
argus 10
argus 100
beta 10
beta 100
beta_prime 10
beta_prime 100
beta_prime_4p 10
beta_prime_4p 100
bradford 10
bradford 100
burr 10
burr 100
burr_4p 10
burr_4p 100
cauchy 10
cauchy 100
chi_square 10
chi_square 100
chi_square_3p 10
chi_square_3p 100
dagum 10
dagum 100
dagum_4p 10
dagum_4p 100
erlang 10
erlang 100
erlang_3p 10
erlang_3p 100
error_function 10
error_function 100
exponential 10
exponential 100
exponential_2p 10
exponential_2p 100
f 10
f 100
fatigue_life 10
fatigue_life 100
folded_normal 10
folded_normal 100
frechet 10
frechet 100
f_4p 10
f_4p 100
gamma 10
gamma 100
gamma_3p 10
gamma_3p 100
generalized_extreme_value 10
generalized_extreme_value 100
generalized_gamma 10
generalized_gamma 100
generalized_gamma_4p 10
generalized_gamma_4p 100
generalized_logistic 10
generalized_logistic 100
generalized_normal 10
generalized_normal 100
generalized_pareto 10
generalized_pareto 100
gibrat 10
gibrat 100
gumbel_left 10
gumbel_left 100
gumbel_right 10
gumbel_right 100
half_normal 10
half_normal 100
hyperbolic_secant 10
hyperbolic_secant 100
inverse_gamma 10
inverse_gamma 100
inverse_gamma_3p 10
inverse_gamma_3p 100
inverse_gaussian 10
inverse_gaussian 100
inverse_gaussian_3p 10
inverse_gaussian_3p 100
johnson_sb 10
johnson_sb 100
johnson_su 10
johnson_su 100
kumaraswamy 10
kumaraswamy 100
laplace 10
laplace 100
levy 10
levy 100
loggamma 10
loggamma 100
logistic 10
logistic 100
loglogistic 10
loglogistic 100
loglogistic_3p 10
loglogistic_3p 100
lognormal 10
lognormal 100
maxwell 10
maxwell 100
moyal 10
moyal 100
nakagami 10
nakagami 100
non_central_chi_square 10
non_central_chi_square 100
non_central_f 10
non_central_f 100
non_central_t_student 10
non_central_t_student 100
normal 10
normal 100
pareto_first_kind 10
pareto_first_kind 100
pareto_second_kind 10
pareto_second_kind 100
pert 10
pert 100
power_function 10
power_function 100
rayleigh 10
rayleigh 100
reciprocal 10
reciprocal 100
rice 10
rice 100
semicircular 10
semicircular 100
trapezoidal 10
trapezoidal 100
triangular 10
triangular 100
t_student 10
t_student 100
t_student_3p 10
t_student_3p 100
uniform 10
uniform 100
weibull 10
weibull 100
weibull_3p 10
weibull_3p 100

In [6]:
df_fit_time

                   10        100
alpha         0.058401  0.128772
arcsine       0.000000  0.000000
argus         0.053560  0.046310
beta          0.097856  0.096450
beta_prime    0.066340  0.038924
...                ...       ...
t_student     0.000000  0.000000
t_student_3p  0.224483  0.207404
uniform       0.000000  0.000000
weibull       0.000000  0.000000
weibull_3p    0.004382  0.002674

[73 rows x 2 columns]